require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AreaBasePricesController do

  # This should return the minimal set of attributes required to create a valid
  # AreaBasePrice. As you add validations to AreaBasePrice, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AreaBasePricesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all area_base_prices as @area_base_prices" do
      area_base_price = AreaBasePrice.create! valid_attributes
      get :index, {}, valid_session
      assigns(:area_base_prices).should eq([area_base_price])
    end
  end

  describe "GET show" do
    it "assigns the requested area_base_price as @area_base_price" do
      area_base_price = AreaBasePrice.create! valid_attributes
      get :show, {:id => area_base_price.to_param}, valid_session
      assigns(:area_base_price).should eq(area_base_price)
    end
  end

  describe "GET new" do
    it "assigns a new area_base_price as @area_base_price" do
      get :new, {}, valid_session
      assigns(:area_base_price).should be_a_new(AreaBasePrice)
    end
  end

  describe "GET edit" do
    it "assigns the requested area_base_price as @area_base_price" do
      area_base_price = AreaBasePrice.create! valid_attributes
      get :edit, {:id => area_base_price.to_param}, valid_session
      assigns(:area_base_price).should eq(area_base_price)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AreaBasePrice" do
        expect {
          post :create, {:area_base_price => valid_attributes}, valid_session
        }.to change(AreaBasePrice, :count).by(1)
      end

      it "assigns a newly created area_base_price as @area_base_price" do
        post :create, {:area_base_price => valid_attributes}, valid_session
        assigns(:area_base_price).should be_a(AreaBasePrice)
        assigns(:area_base_price).should be_persisted
      end

      it "redirects to the created area_base_price" do
        post :create, {:area_base_price => valid_attributes}, valid_session
        response.should redirect_to(AreaBasePrice.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved area_base_price as @area_base_price" do
        # Trigger the behavior that occurs when invalid params are submitted
        AreaBasePrice.any_instance.stub(:save).and_return(false)
        post :create, {:area_base_price => {}}, valid_session
        assigns(:area_base_price).should be_a_new(AreaBasePrice)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AreaBasePrice.any_instance.stub(:save).and_return(false)
        post :create, {:area_base_price => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested area_base_price" do
        area_base_price = AreaBasePrice.create! valid_attributes
        # Assuming there are no other area_base_prices in the database, this
        # specifies that the AreaBasePrice created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AreaBasePrice.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => area_base_price.to_param, :area_base_price => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested area_base_price as @area_base_price" do
        area_base_price = AreaBasePrice.create! valid_attributes
        put :update, {:id => area_base_price.to_param, :area_base_price => valid_attributes}, valid_session
        assigns(:area_base_price).should eq(area_base_price)
      end

      it "redirects to the area_base_price" do
        area_base_price = AreaBasePrice.create! valid_attributes
        put :update, {:id => area_base_price.to_param, :area_base_price => valid_attributes}, valid_session
        response.should redirect_to(area_base_price)
      end
    end

    describe "with invalid params" do
      it "assigns the area_base_price as @area_base_price" do
        area_base_price = AreaBasePrice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AreaBasePrice.any_instance.stub(:save).and_return(false)
        put :update, {:id => area_base_price.to_param, :area_base_price => {}}, valid_session
        assigns(:area_base_price).should eq(area_base_price)
      end

      it "re-renders the 'edit' template" do
        area_base_price = AreaBasePrice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AreaBasePrice.any_instance.stub(:save).and_return(false)
        put :update, {:id => area_base_price.to_param, :area_base_price => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested area_base_price" do
      area_base_price = AreaBasePrice.create! valid_attributes
      expect {
        delete :destroy, {:id => area_base_price.to_param}, valid_session
      }.to change(AreaBasePrice, :count).by(-1)
    end

    it "redirects to the area_base_prices list" do
      area_base_price = AreaBasePrice.create! valid_attributes
      delete :destroy, {:id => area_base_price.to_param}, valid_session
      response.should redirect_to(area_base_prices_url)
    end
  end

end
